require('dotenv').config();

//Secure defaults
const DEFAULT_PORT = process.env.PORT || 3001;
const DEFAULT_HOST = process.env.HOST || '0.0.0.0';
const DEFAULT_REDIS_URL = process.env.DEFAULT_REDIS_URL || "redis://127.0.0.1:6379";
const DEFAULT_REDIS_TLS = process.env.REDIS_TLS || true;
const DEFAULT_REDIS_TTL_MINUTES = process.env.REDIS_TTL_MINUTES || 15;
const DEFAULT_REAUTH_WINDOW_MS = process.env.REAUTH_WINDOW_MS || 5 * 60 * 1000
let DEFAULT_SECURE = true;
let DEFAULT_HTTP_ONLY = true;
let DEFAULT_SAME_SITE = "strict";
let DEFAULT_CORS_ALLOWED_ORIGINS = ['http://localhost:3000', 'http://localhost:5173', 'https://localhost:5173', 'http://localhost:6006']
let ALLOW_EMPTY_ORIGIN = false;
let DEFAULT_CORS_ENABLED = true;

//Initialize secrets as undefined
let DEFAULT_ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET;
let DEFAULT_REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET;
let DEFAULT_SESSION_SECRET = process.env.SESSION_SECRET;
let DEFAULT_INTERNAL_API_KEY = process.env.INTERNAL_API_KEY;
let DEFAULT_JWT_SECRET = process.env.JWT_SECRET;

//Apply development-specific adjustments
if (process.env.NODE_ENV === 'development') {
  DEFAULT_ACCESS_TOKEN_SECRET = DEFAULT_ACCESS_TOKEN_SECRET || "J2Adgc7PqyMT6qB+KxhlTYpyRHqp4gI7C8WDkbEVve9HJ4UFtE8DW91dg0Px1EBu";
  DEFAULT_JWT_SECRET = DEFAULT_JWT_SECRET || "J2Adgc7PqyMT6qB+KxhlTYpyRHqp4gI7C8WDkbEVve9HJ4UFtE8DW91dg0Px1EBu";
  DEFAULT_REFRESH_TOKEN_SECRET = DEFAULT_REFRESH_TOKEN_SECRET || "sWFEpzloPT5tO4mL/jOzY5hoQd3V5I1r7uxu3faJhbilTw7WDI5pEEgPDoh2DvjS";
  DEFAULT_SESSION_SECRET = DEFAULT_SESSION_SECRET || "S3QvY9RW8QXYNXWvePduQHpKmCKTrrQ2vZWMzmLfvltuwo1/ZX7PX81LzeVTq/30";
  DEFAULT_INTERNAL_API_KEY = DEFAULT_INTERNAL_API_KEY || "CCbN63OPOxjYwzJdqgvtPoF1YIMvdL6EIX+vKDBISURB1HaJ8SOdpWaHg5WPxKyU"
  DEFAULT_HTTP_ONLY = false;
  DEFAULT_SECURE = false;
  DEFAULT_SAME_SITE = process.env.SAME_SITE || 'Lax';
  DEFAULT_CORS_ALLOWED_ORIGINS = process.env.CORS_ALLOWED_ORIGINS
    ? process.env.CORS_ALLOWED_ORIGINS.split(',')
    : DEFAULT_CORS_ALLOWED_ORIGINS;
  ALLOW_EMPTY_ORIGIN = true;
  DEFAULT_CORS_ENABLED = true;
}

//Enforce secrets presence
if (!DEFAULT_ACCESS_TOKEN_SECRET || !DEFAULT_REFRESH_TOKEN_SECRET || !DEFAULT_JWT_SECRET) {
  throw new Error("JWT_SECRET, ACCESS_TOKEN_SECRET and REFRESH_TOKEN_SECRET must be set in all enviroments.");
}

//Final constants for export
const ACCESS_TOKEN_SECRET = DEFAULT_ACCESS_TOKEN_SECRET;
const REFRESH_TOKEN_SECRET = DEFAULT_REFRESH_TOKEN_SECRET;
const SESSION_SECRET = DEFAULT_SESSION_SECRET;
const PORT = DEFAULT_PORT;
const HOST = DEFAULT_HOST;
const SECURE = DEFAULT_SECURE;
const HTTP_ONLY = DEFAULT_HTTP_ONLY;
const SAME_SITE_TYPES = { STRICT: "Strict", LAX: "Lax", NONE: "None" };
const SAME_SITE = SAME_SITE_TYPES[DEFAULT_SAME_SITE.toUpperCase()] || SAME_SITE_TYPES.STRICT;
const CORS_ALLOWED_ORIGINS = DEFAULT_CORS_ALLOWED_ORIGINS;
const REDIS_URL = DEFAULT_REDIS_URL;
const REDIS_TLS = DEFAULT_REDIS_TLS;
const REDIS_TTL_MINUTES = DEFAULT_REDIS_TTL_MINUTES;
const CORS_ENABLED = DEFAULT_CORS_ENABLED;
const REAUTH_WINDOW_MS = DEFAULT_REAUTH_WINDOW_MS;
const INTERNAL_API_KEY = DEFAULT_INTERNAL_API_KEY;
const JWT_SECRET = DEFAULT_JWT_SECRET;

//Add DB and ReCAPTCHA
const DB_CONNECTION_STRING = process.env.DB_CONNECTION_STRING;
const SECRET_RECAPTCHA_SERVER_KEY = process.env.SECRET_RECAPTCHA_SERVER_KEY;

//Validate DB and ReCAPTCHA
if (!DB_CONNECTION_STRING) throw new Error("DB_CONNECTION_STRING must be set.");
if (!SECRET_RECAPTCHA_SERVER_KEY) throw new Error("SECRET_RECAPTCHA_SERVER_KEY must be set.");

module.exports = {
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_SECRET,
  SESSION_SECRET,
  PORT,
  HOST,
  SECURE,
  HTTP_ONLY,
  SAME_SITE,
  SAME_SITE_TYPES,
  CORS_ALLOWED_ORIGINS,
  ALLOW_EMPTY_ORIGIN,
  DB_CONNECTION_STRING,
  SECRET_RECAPTCHA_SERVER_KEY,
  REDIS_URL,
  REDIS_TLS,
  REDIS_TTL_MINUTES,
  CORS_ENABLED,
  REAUTH_WINDOW_MS,
  INTERNAL_API_KEY,
  JWT_SECRET
}